(library
 (name kido_test)
 (flags
  (:standard -open Containers))
 (libraries kido tmux containers unix yojson mtime threads.posix)
 (inline_tests
  (deps
   ../pi/testdata/discriminator.json
   ../pi/testdata/tools.json
   ../bin/main.exe
   (source_tree %{project_root}/shims)
   %{project_root}/pi/kido-status.ts
   %{project_root}/pi/kido-agents.ts
   %{project_root}/claude/settings.json))
 (preprocess
  (pps ppx_expect)))
