(library
 (name kido)
 (flags
  (:standard -open Containers))
 (libraries
  containers
  dune-build-info
  unix
  yojson
  mtime
  mtime.clock
  tmux
  mosaic
  matrix
  matrix.text
  threads.posix)
 (preprocess
  (pps ppx_deriving_yojson)))

(rule
 (target embedded.ml)
 (deps
  %{project_root}/share/zsh/integration.zsh
  %{project_root}/share/bash/integration.bash
  %{project_root}/share/tmux/kido-tmux.conf)
 (action
  (with-stdout-to
   %{target}
   (progn
    (echo "let zsh_integration = {kido|")
    (cat %{project_root}/share/zsh/integration.zsh)
    (echo "|kido}\n\nlet bash_integration = {kido|")
    (cat %{project_root}/share/bash/integration.bash)
    (echo "|kido}\n\nlet tmux_defaults = {kido|")
    (cat %{project_root}/share/tmux/kido-tmux.conf)
    (echo "|kido}\n")))))
