(library
 (name kido_fs)
 (wrapped false)
 (modules fs)
 (flags
  (:standard -open Containers))
 (libraries containers unix yojson ppx_yojson_conv_lib)
 (inline_tests)
 (preprocess
  (pps ppx_expect)))

(library
 (name kido)
 (modules
  (:standard \ fs))
 (flags
  (:standard
   -open
   Containers
   -open
   Ppx_compare_lib.Builtin
   -open
   Ppx_yojson_conv_lib.Yojson_conv.Primitives))
 (libraries
  kido_fs
  containers
  dune-build-info
  unix
  yojson
  mtime
  mtime.clock
  tmux
  threads.posix)
 (inline_tests
  (deps
   ../bin/main.exe
   (source_tree %{project_root}/share/bin)
   %{project_root}/share/shim.sh
   %{project_root}/share/pi/kido-status.ts
   %{project_root}/share/pi/kido-agents.ts))
 (preprocess
  (pps ppx_yojson_conv ppx_compare ppx_string_conv ppx_expect)))

(rule
 (target embedded.ml)
 (deps
  %{project_root}/share/zsh/integration.zsh
  %{project_root}/share/bash/integration.bash
  %{project_root}/share/tmux/kido-tmux.conf)
 (action
  (with-stdout-to
   %{target}
   (progn
    (echo "let zsh_integration = {kido|")
    (cat %{project_root}/share/zsh/integration.zsh)
    (echo "|kido}\n\nlet bash_integration = {kido|")
    (cat %{project_root}/share/bash/integration.bash)
    (echo "|kido}\n\nlet tmux_defaults = {kido|")
    (cat %{project_root}/share/tmux/kido-tmux.conf)
    (echo "|kido}\n")))))
