type server = Down | Up | Mismatch

let socket = "kido"

let tmux_safe what s =
  match Seq.find (String.contains "'\"$#\\`\n\r") (String.to_seq s) with
  | Some c ->
      Error
        (Printf.sprintf
           "refusing %s %S: it contains %S, which cannot survive tmux's own command-line parsing"
           what s (String.make 1 c))
  | None -> Ok ()

let conf_command path args =
  match tmux_safe "path" path with
  | Error e -> Error ("cannot start a kido server: " ^ e)
  | Ok () ->
      let inner =
        if String.exists (fun c -> Char.equal c ' ' || Char.equal c '\t') path then
          {|"|} ^ path ^ {|"|}
        else path
      in
      Ok ("'" ^ String.concat " " (inner :: args) ^ "'")

let user_conf ~xdg_config_home ~home =
  if not (String.is_empty xdg_config_home) then
    Ok (Filename.concat xdg_config_home "kido/kido.conf")
  else if String.is_empty home then Error "$HOME is not defined"
  else Ok (Filename.concat home ".config/kido/kido.conf")

let server_conf ~exe ~user_conf =
  let open Result.Infix in
  let* kido = conf_command exe [] in
  let* kido_shell = conf_command exe [ "shell" ] in
  if String.exists (String.contains "'\n\r") user_conf then
    Error (Printf.sprintf "cannot source %s: the path contains a quote or a newline" user_conf)
  else
    Ok
      (String.concat ""
         [
           Printf.sprintf
             "# Generated by kido on every launch; edits here are lost.\n\
              # Your own configuration belongs in %s.\n\n"
             user_conf;
           Embedded.tmux_defaults;
           Printf.sprintf
             "\n\
              # The user's configuration, if there is one: -q, because there\n\
              # usually is not.\n\
              source-file -q '%s'\n"
             user_conf;
           Printf.sprintf
             "\n\
              # What kido owns, set last so nothing above can take it away. The\n\
              # side column and every pane's shell run this kido by the path it\n\
              # was started as, so a second install elsewhere on PATH cannot\n\
              # answer for this server. A default-command the user set above is\n\
              # kept for `kido shell` to run, primed, in place of a bare shell.\n\
              set -gF %s '#{default-command}'\n\
              set -g side-status-command %s\n\
              set -g default-command %s\n"
             Shell.user_command_option kido kido_shell;
         ])

(* tmux's own wording, from client.c, is "protocol version mismatch (client N, server M)": what
   a kido-tmux upgraded under a running server answers every new client until that server
   restarts. *)
let probe_server bin =
  let ((out, _, err) as p) =
    Unix.open_process_args_full bin [| bin; "-L"; socket; "list-sessions" |] (Unix.environment ())
  in
  ignore (In_channel.input_all out);
  let stderr = In_channel.input_all err in
  match Unix.close_process_full p with
  | WEXITED 0 -> Up
  | _ when String.mem ~sub:"protocol version mismatch" stderr -> Mismatch
  | _ -> Down

let run ~tmux =
  let open Result.Infix in
  if not (String.is_empty tmux) then
    Error
      (Printf.sprintf "already inside tmux (%s); run kido from a plain terminal"
         (List.hd (String.split_on_char ',' tmux)))
  else
    let bin = Lazy.force Tmux.Exec.binary in
    let exec env args = Unix.execvpe bin (Array.of_list (bin :: "-L" :: socket :: args)) env in
    match probe_server bin with
    | Mismatch ->
        Error
          (Printf.sprintf
             "the kido server on socket %S is running an older kido-tmux than this one, so it \
              refuses this client; restart it once its windows are free (detach, then %s -L %s \
              kill-server)"
             socket bin socket)
    | Up -> exec (Unix.environment ()) [ "attach-session" ]
    | Down ->
        let env name = Option.get_or ~default:"" (Sys.getenv_opt name) in
        let exe = Tmux.Exec.invoked_path ~path:(env "PATH") Sys.argv.(0) in
        let* user_conf = user_conf ~xdg_config_home:(env "XDG_CONFIG_HOME") ~home:(env "HOME") in
        let conf = Filename.concat (State.dir ()) "server.conf" in
        Fs.mkdir_p (State.dir ());
        let* conf_text = server_conf ~exe ~user_conf in
        Fs.write conf conf_text;
        let env =
          match Bin_dir.of_exe exe with
          | Some dir ->
              Shell.with_env (Unix.environment ())
                [ ("PATH", Bin_dir.path_with_first dir (env "PATH")) ]
          | None -> Unix.environment ()
        in
        exec env [ "-f"; conf; "new-session"; "-s"; "main" ]
