type server = Down | Up of string option | Mismatch

type endpoint = { tmux : string; socket : string; protocol : string; server : string option }
[@@deriving to_yojson]

let tmux_safe what s =
  match Seq.find (String.contains "'\"$#\\`\n\r") (String.to_seq s) with
  | Some c ->
      Error
        (Printf.sprintf
           "refusing %s %S: it contains %S, which cannot survive tmux's own command-line parsing"
           what s (String.make 1 c))
  | None -> Ok ()

let conf_command path args =
  match tmux_safe "path" path with
  | Error e -> Error ("cannot start a kido server: " ^ e)
  | Ok () ->
      let inner =
        if String.exists (fun c -> Char.equal c ' ' || Char.equal c '\t') path then
          {|"|} ^ path ^ {|"|}
        else path
      in
      Ok ("'" ^ String.concat " " (inner :: args) ^ "'")

let user_conf ~xdg_config_home ~home =
  if not (String.is_empty xdg_config_home) then
    Ok (Filename.concat xdg_config_home "kido/kido.conf")
  else if String.is_empty home then Error "$HOME is not defined"
  else Ok (Filename.concat home ".config/kido/kido.conf")

let server_conf ~exe ~user_conf =
  let open Result.Infix in
  let* kido = conf_command exe [] in
  let* kido_shell = conf_command exe [ "shell" ] in
  if String.exists (String.contains "'\n\r") user_conf then
    Error (Printf.sprintf "cannot source %s: the path contains a quote or a newline" user_conf)
  else
    Ok
      (String.concat ""
         [
           Printf.sprintf
             "# Generated by kido on every launch; edits here are lost.\n\
              # Your own configuration belongs in %s.\n\n"
             user_conf;
           Embedded.tmux_defaults;
           Printf.sprintf
             "\n\
              # The user's configuration, if there is one: -q, because there\n\
              # usually is not.\n\
              source-file -q '%s'\n"
             user_conf;
           Printf.sprintf
             "\n\
              # What kido owns, set last so nothing above can take it away. The\n\
              # side column and every pane's shell run this kido by the path it\n\
              # was started as, so a second install elsewhere on PATH cannot\n\
              # answer for this server. A default-command the user set above is\n\
              # kept for `kido shell` to run, primed, in place of a bare shell.\n\
              set -gF %s '#{default-command}'\n\
              set -g side-status-command %s\n\
              set -g default-command %s\n"
             Shell.user_command_option kido kido_shell;
         ])

(* tmux's own wording, from client.c, is "protocol version mismatch (client N, server M)": what
   a kido-tmux upgraded under a running server answers every new client until that server
   restarts. *)
let probe_server ~socket bin =
  let ((out, _, err) as p) =
    Unix.open_process_args_full bin
      (Tmux.argv bin
         [
           "-S";
           socket;
           "list-sessions";
           "-F";
           "#{socket_path}\x1f";
           ";";
           "show-environment";
           "-g";
           "KIDO_PROTOCOL";
         ])
      (Unix.environment ())
  in
  let stdout = In_channel.input_all out in
  let stderr = In_channel.input_all err in
  match Unix.close_process_full p with
  | _ when String.mem ~sub:"protocol version mismatch" stderr -> Mismatch
  | WEXITED (0 | 1) -> (
      let lines = String.split_on_char '\n' stdout in
      match String.split_on_char '\x1f' (List.hd lines) with
      | [ socket; "" ] when not (String.is_empty socket) ->
          let protocol =
            List.find_map
              (fun line ->
                String.chop_prefix ~pre:"KIDO_PROTOCOL=" line
                |> Option.filter (fun value -> not (String.is_empty value)))
              lines
          in
          Up protocol
      | _ -> Down)
  | _ -> Down

let mismatch ~socket bin =
  Printf.sprintf
    "the kido server on socket %S is running an older kido-tmux than this one, so it refuses this \
     client; restart it once its windows are free (detach, then %s -S %s kill-server)"
    socket bin socket

let argv ~socket bin args = Tmux.argv bin ("-S" :: socket :: args)

let new_session ~dir ~detach =
  let open Result.Infix in
  let* user_conf =
    user_conf ~xdg_config_home:(Fs.getenv "XDG_CONFIG_HOME") ~home:(Fs.getenv "HOME")
  in
  let conf = Filename.concat dir "server.conf" in
  let* conf_text = server_conf ~exe:(Lazy.force Fs.self) ~user_conf in
  Fs.write conf conf_text;
  let env =
    Shell.with_env
      (Array.filter (fun s -> not (String.prefix ~pre:"KIDO_STATE_DIR=" s)) (Unix.environment ()))
      [ ("KIDO_PROTOCOL", Protocol.value) ]
  in
  let env =
    match Bin_dir.own () with
    | Some dir -> Shell.with_env env [ ("PATH", Bin_dir.path_with_first dir (Fs.getenv "PATH")) ]
    | None -> env
  in
  Ok (env, [ "-f"; conf; "new-session" ] @ (if detach then [ "-d" ] else []) @ [ "-s"; "main" ])

let run ~dir ~tmux =
  let open Result.Infix in
  if not (String.is_empty tmux) then
    Error
      (Printf.sprintf "already inside tmux (%s); run kido from a plain terminal"
         (List.hd (String.split_on_char ',' tmux)))
  else
    let* socket = State.server_socket ~create:true ~dir in
    let bin = Lazy.force Tmux.binary in
    match probe_server ~socket bin with
    | Mismatch -> Error (mismatch ~socket bin)
    | Up _ -> Unix.execvpe bin (argv ~socket bin [ "attach-session" ]) (Unix.environment ())
    | Down ->
        let* env, args = new_session ~dir ~detach:false in
        Unix.execvpe bin (argv ~socket bin args) env

let ensure ~dir =
  let open Result.Infix in
  let* socket = State.server_socket ~create:true ~dir in
  let bin = Lazy.force Tmux.binary in
  let resolve server =
    let tmux =
      if String.contains bin '/' then Some (Fs.abs bin)
      else Fs.look_path ~path:(Fs.getenv "PATH") bin
    in
    match tmux with
    | Some tmux -> Ok { tmux; socket; protocol = Protocol.value; server }
    | None -> Error (Printf.sprintf "no %s on PATH" bin)
  in
  match probe_server ~socket bin with
  | Up protocol -> resolve protocol
  | Mismatch -> Error (mismatch ~socket bin)
  | Down -> (
      let* env, args = new_session ~dir ~detach:true in
      let ((out, _, err) as p) = Unix.open_process_args_full bin (argv ~socket bin args) env in
      ignore (In_channel.input_all out);
      let stderr = String.trim (In_channel.input_all err) in
      ignore (Unix.close_process_full p);
      match probe_server ~socket bin with
      | Up protocol -> resolve protocol
      | Mismatch -> Error (mismatch ~socket bin)
      | Down ->
          Error ("cannot start a kido server" ^ if String.is_empty stderr then "" else ": " ^ stderr)
      )

let%test_module "Tests" =
  (module struct
    let%expect_test "rpc surface" =
      let emit json = print_endline (Yojson.Safe.to_string json) in
      List.iter
        (fun server ->
          emit
            (endpoint_to_yojson
               {
                 tmux = "/bin/kido-tmux";
                 socket = "/server/socket";
                 protocol = Protocol.value;
                 server;
               }))
        [ Some Protocol.value; Some "other"; None ];
      [%expect
        {|
    {"tmux":"/bin/kido-tmux","socket":"/server/socket","protocol":"2.1","server":"2.1"}
    {"tmux":"/bin/kido-tmux","socket":"/server/socket","protocol":"2.1","server":"other"}
    {"tmux":"/bin/kido-tmux","socket":"/server/socket","protocol":"2.1","server":null}
  |}]
  end)
