package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"

	"kido/internal/state"
	"kido/internal/tmux"
	tmuxconf "kido/tmux"
)

// kido-tmux never shares a server with a stock tmux: the two speak
// different protocol versions.
const kidoSocket = "kido"

func launch() error {
	if inside := os.Getenv("TMUX"); inside != "" {
		return fmt.Errorf("already inside tmux (%s); run kido from a plain terminal",
			strings.SplitN(inside, ",", 2)[0])
	}
	bin := tmux.Binary()
	switch probeServer(bin) {
	case serverMismatch:
		return fmt.Errorf("the kido server on socket %q is running an older kido-tmux than this one, "+
			"so it refuses this client; restart it once its windows are free (detach, then "+
			"%s -L %s kill-server)", kidoSocket, bin, kidoSocket)
	case serverUp:
		return execTmux(bin, os.Environ(), "-L", kidoSocket, "attach-session")
	}
	conf, err := writeServerConf()
	if err != nil {
		return err
	}
	env := os.Environ()
	if dir, ok := ownBinDir(); ok {
		env = withEnv(env, []string{"PATH=" + pathWithFirst(dir, os.Getenv("PATH"))})
	}
	return execTmux(bin, env, "-L", kidoSocket, "-f", conf, "new-session", "-s", "main")
}

func execTmux(bin string, env []string, args ...string) error {
	path, err := exec.LookPath(bin)
	if err != nil {
		return err
	}
	return syscall.Exec(path, append([]string{bin}, args...), env)
}

// serverState is what the kido socket answered when kido asked.
type serverState int

const (
	serverDown serverState = iota
	serverUp
	serverMismatch
)

// tmux's own wording, from client.c, is "protocol version mismatch
// (client N, server M)" - what a kido-tmux upgraded under a running
// server answers every new client until that server restarts.
func probeServer(bin string) serverState {
	cmd := exec.Command(bin, "-L", kidoSocket, "list-sessions")
	var errb bytes.Buffer
	cmd.Stderr = &errb
	switch {
	case cmd.Run() == nil:
		return serverUp
	case strings.Contains(errb.String(), "protocol version mismatch"):
		return serverMismatch
	}
	return serverDown
}

// The user's own ~/.tmux.conf is deliberately not read: a config written
// for stock tmux fights the side column.
func userConfPath() (string, error) {
	if dir := os.Getenv("XDG_CONFIG_HOME"); dir != "" {
		return filepath.Join(dir, "kido", "kido.conf"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "kido", "kido.conf"), nil
}

// tmuxConfUnsafe are the characters a string cannot contain and still be
// written into a tmux command that nests parsers: tmux's own, then sh's,
// and tmux's again for anything that reaches a further tmux command. No
// escape survives all three - a single quote would end tmux's string, and
// `$`, `#`, a backslash or a backtick would be expanded by sh or by tmux
// rather than taken literally.
const tmuxConfUnsafe = "'\"$#\\`\n\r"

func tmuxSafe(what, s string) error {
	if i := strings.IndexAny(s, tmuxConfUnsafe); i >= 0 {
		return fmt.Errorf("refusing %s %q: it contains %q, which cannot survive tmux's own command-line parsing", what, s, s[i:i+1])
	}
	return nil
}

// Both side-status-command and default-command are command strings tmux
// hands to /bin/sh after expanding them as formats, so the word is
// single-quoted for tmux and, only when the path itself needs it, double-
// quoted for the shell inside that.
//
// The inner double quotes are otherwise left off on purpose: this string
// is also what tmux's own default_window_name() (third_party/tmux/names.c)
// parses to name a window with automatic-rename off, and it strips at
// most one layer of quoting - a path wrapped in quotes it does not need
// survives as a single backslash, not as its basename.
func confCommand(path string, args ...string) (string, error) {
	if err := tmuxSafe("path", path); err != nil {
		return "", fmt.Errorf("cannot start a kido server: %w", err)
	}
	inner := path
	if strings.ContainsAny(path, " \t") {
		inner = `"` + path + `"`
	}
	word := "'" + inner
	for _, a := range args {
		word += " " + a
	}
	return word + "'", nil
}

func writeServerConf() (string, error) {
	exe, err := tmux.InvokedPath(os.Args[0])
	if err != nil {
		return "", err
	}
	kido, err := confCommand(exe)
	if err != nil {
		return "", err
	}
	kidoShell, err := confCommand(exe, "shell")
	if err != nil {
		return "", err
	}
	userConf, err := userConfPath()
	if err != nil {
		return "", err
	}
	if strings.ContainsAny(userConf, "'\n\r") {
		return "", fmt.Errorf("cannot source %s: the path contains a quote or a newline", userConf)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by kido on every launch; edits here are lost.\n"+
		"# Your own configuration belongs in %s.\n\n", userConf)
	b.Write(tmuxconf.Defaults)
	fmt.Fprintf(&b, "\n# The user's configuration, if there is one: -q, because there\n"+
		"# usually is not.\nsource-file -q '%s'\n", userConf)
	fmt.Fprintf(&b, "\n# What kido owns, set last so nothing above can take it away. The\n"+
		"# side column and every pane's shell run this kido by the path it\n"+
		"# was started as, so a second install elsewhere on PATH cannot\n"+
		"# answer for this server. A default-command the user set above is\n"+
		"# kept for `kido shell` to run, primed, in place of a bare shell.\n"+
		"set -gF %s '#{default-command}'\n"+
		"set -g side-status-command %s\n"+
		"set -g default-command %s\n", userCommandOption, kido, kidoShell)

	path := filepath.Join(state.Dir(), "server.conf")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, b.Bytes(), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
