// dump-prompts.ts prints every piece of text kido's pi extensions put in
// front of a model: each tool's description, prompt snippet, prompt
// guidelines and parameter descriptions, and the system prompt appended
// to a subagent. It loads
// pi/kido-agents.ts against a stub of pi's ExtensionAPI, the same way the
// test suite does, so what it prints is what pi registers.
//
//   node --experimental-strip-types scripts/dump-prompts.ts > prompts.md
//
// The texts the extension injects as messages at runtime (an inbound ask,
// a steer, a task, a notice, a stream batch) are built inside closures and
// are listed in the second half by hand, with the line they come from.

const tools: any[] = [];
let systemPrompt: ((event: { systemPrompt: string }) => { systemPrompt: string } | undefined) | undefined;
const pi = {
  registerTool: (t: any) => tools.push(t),
  on: (event: string, handler: any) => {
    if (event === "before_agent_start") systemPrompt = handler;
  },
  registerMessageRenderer: () => {},
  sendMessage: () => {},
  sendUserMessage: () => {},
};
// The subagent instruction is appended only when this process is a
// subagent, which the extension decides by matching its own pi session id
// against the run id kido handed it. Both are faked here, and the
// environment goes in before the import, since the module reads it at
// its top level.
process.env.KIDO_AGENT_PARENT_INSTANCE = "dump";
process.env.KIDO_AGENT_RUN_ID = "dump-run";
const seam = ((globalThis as any)[Symbol.for("kido.pi.extension.seam")] ??= {});
seam.host = { sessionId: () => "dump-run" };
const { default: kidoAgents } = await import("../pi/kido-agents.ts");
kidoAgents(pi as any);

const out: string[] = ["# What the model sees from kido's pi extensions", ""];
out.push("Generated by scripts/dump-prompts.ts from pi/kido-agents.ts. Edit the source, not this file.", "");

out.push("## System prompt appended to a subagent (before_agent_start)", "");
const sp = systemPrompt?.({ systemPrompt: "<host system prompt>" });
out.push("```", (sp?.systemPrompt ?? "<none>").replace("<host system prompt>\n\n", ""), "```", "");

out.push("## Tools", "");
for (const t of tools) {
  out.push(`### ${t.name}`, "");
  out.push("description:", "", "```", t.description, "```", "");
  out.push("promptSnippet:", "", "```", t.promptSnippet ?? "<none>", "```", "");
  if (t.promptGuidelines?.length) {
    out.push("promptGuidelines (merged into the system prompt's rules while the tool is registered):", "", "```", t.promptGuidelines.join("\n"), "```", "");
  }
  const props = t.parameters?.properties ?? {};
  const required = new Set<string>(t.parameters?.required ?? []);
  if (Object.keys(props).length === 0) {
    out.push("parameters: none", "");
    continue;
  }
  out.push("parameters:", "");
  for (const [name, schema] of Object.entries<any>(props)) {
    const type = schema.type === "array" ? `${schema.items?.type ?? "any"}[]` : schema.type;
    out.push(`- \`${name}\` (${type}${required.has(name) ? ", required" : ""}): ${schema.description ?? "<no description>"}`);
  }
  out.push("");
}
out.push("## Messages the extension injects at runtime", "");
out.push("Built inside pi/kido-agents.ts's closures; quoted here with their source line. `<from>` is the sender's name, else its session id, else its pane, else \"another agent\".", "");
const injected: Array<[string, string, string]> = [
  ["a spawned task (deliverTask)", "the task text verbatim, as a user message, once", ""],
  ["an inbound ask (handleInboundAsk)", "<from> is asking (id <id>): <question>\n\n<from> cannot see this session's context, so make the answer self-contained. Reply with message_agent(to=\"<from>\", message=<answer>, replyTo=\"<id>\"). That message_agent call is the entire response - end the turn there, with no summary or sign-off after it.", "followUp"],
  ["a reply nobody is waiting for (handleInboundReply)", "<from> replied (to ask <id>): <text>", "followUp"],
  ["a message from another agent", "message from @<name> (your parent, who spawned you): | (your subagent): | (another agent in this session, not the user):\n<text> verbatim, as a custom message of type kido-message; the TUI takes the header back off and shows \"message from @<name>:\" with the text in full, never collapsed", "followUp"],
  ["a message with no agent sender", "<text> verbatim, unlabelled: a human running `kido message_agent` from a pane with no state record is the user speaking", "followUp"],
  ["a steer from an ancestor (handleInboundSteer)", "<from> is redirecting this work: <text>", "steer"],
  ["a notice (deliverNotice)", "notice from <from> (a subagent or background run's report, not the user):\n<text> verbatim, as a custom message of type kido-notice; the TUI takes the header back off and shows it collapsed as \"notification from <from>: <first line>\"", "steer"],
  ["a stream batch (flushStreams)", "async run \"<name>\" output (run <id>)\n<the last lines, capped>; with lines dropped: \"... N lines omitted (see <output path>)\" first", "steer, at a moment that costs no turn"],
  ["an unknown kind", "[unrecognised message kind \"<kind>\" from <from>] <text>", "followUp"],
  ["message_agent's result while answering an ask", "delivered to <to> by inbox That message_agent call is the entire response - end the turn there, with no summary or sign-off after it.", "tool result"],
];
for (const [when, text, how] of injected) {
  out.push(`### ${when}`, "", "```", text, "```", how ? `delivered as: ${how}` : "", "");
}
out.push("## Notices kido itself composes (Go)", "");
out.push("cmd/kido/ending_notice.go, sent to the parent when a run ends without the child reporting; cmd/kido/report.go for a report over the cap.", "");
out.push("```", `async run "<name>" <result>: <text>
run: <id>
output: <path>
<N> lines not streamed (the output file above has every one)   [only when streaming dropped lines]
--- last <n> bytes of output (<m> omitted) ---   | --- output --- | --- no output --- | --- output unreadable: <err> ---
<tail>`, "```", "");
out.push("```", `subagent "<name>" <result> without reporting: it never called notify_parent, so this is the whole account of it
detail: <text>   [when there is one]
run: <id>
resume: spawn_subagent(resume: "<id>")`, "```", "");
out.push("A notify_parent report over 4000 bytes is sent as its head plus:", "", "```", "\n\nfull report: <path>", "```", "");
process.stdout.write(out.join("\n"));
